name: Knowledge Base (Prod)

on:
  push:
    branches:
      - "main"

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Sync Markdown Files to S3
      run: |
        aws s3 sync ./articles s3://skillhunt-knowledge-base-prod/ --exclude "*" --include "*.md"
